[battery]
charging_symbol = " "
discharging_symbol = " "
full_symbol = " "

[[battery.display]]
style = "bold red"
threshold = 20

[character]
error_symbol = ""
symbol = ""
use_symbol_for_status = true
vicmd_symbol = ""

[cmd_duration]
min_time = 1

[git_branch]
symbol = " "

[jobs]
symbol = " "

[kubernetes]
symbol = "ﴱ "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "
