Settings:  # Settings app
  Network:  # Either Wi-Fi or wired connection
    IPv4:
      DNS:
        Automatic: false
        Addresses:
          - 1.1.1.1  # Cloudflare public DNS resolver
          - 1.0.0.1
    IPv6:
      DNS:
        Automatic: false
        Addresses:
          - 2606:4700:4700::1111
          - 2606:4700:4700::1001
  Background:
    Background: wallpaper.jpg  # in ~/Pictures
    LockScreen: wallpaper.jpg
  Notifications:
    NotificationPopups: false
    LockScreenNotifications: false
  Privacy:
    PurgeTrashAndTemporaryFiles:
      AutomaticallyEmptyTrash: true
      AutomaticallyPurgeTemporaryFiles: true
    ProblemReporting:
      SendReportsAutomatically: true
  Sound:
    SoundEffects:
      AlertVolume: false
  Devices:
    Displays:
      NightLight: true
      Schedule: Sunset to Sunrise
    Keyboard:
      CustomShortcuts:
        Add:
          - Restart system, SUPER + SHIFT + R, gnome-session-quit --reboot
          - Shutdown system, SUPER + SHIFT + P, gnome-session-quit --power-off
          - Suspend system, SUPER + SHIFT + S, systemctl suspend
        Remove:
          - tilix-quake, F12
          - Show/Hide Tilix Quake Console, F12
  Details:
    DateAndTime:
      AutomaticTimeZone: true
